### PR TITLE
If (@error > 0) Then _ERROR

### PR DESCRIPTION
**Pull request by mlipok**
@donnyh13 I wonder why did you use:
```autoit
If (@error > 0) Then _ERROR
```
instead
```autoit
If @error Then _ERROR
``

### CODE REVIEW

**Comment by donnyh13** [comment]
I felt it was clearer what I was checking for (for any looking at the code). But I could swap to 
> if @error then _Error
If you want.

**Review by donnyh13 — APPROVED** [review]
Looks good. Thank you.

**Comment by mlipok** [comment]
> I felt it was clearer what I was checking for (for any looking at the code).

there was an inconsistency, the example files checked for errors differently than the UDF itself.
This form 
```autoit
If @error Then _ERROR
```

is generally more often used because it is simpler

**Comment by donnyh13** [comment]
Okay. Will remember to use that method. Thank you.

**Pull request merged**
