### PR TITLE
Added Images Functions. Split Shapes off.

### PR DESCRIPTION
**Pull request by donnyh13**

### CODE REVIEW

**Comment by mlipok** [comment]
Thanks for new features.
Must take a closer look.

**Comment by donnyh13** [comment]
Okay. 

- I am unable to insert images as "Linked". The method by Pitonyak doesn't do it, they are only inserted as embedded. Going to guess it's not possible? I could use a dispatch, but it brings up a prompt which the user would have to click.
- Also setting Invert in _LOWriter_ImageColorAdjust is glitchy. 
- And I can't find a way to set "Filters" for an image. 
- And I omitted Previous and Next link (Image>Properties>Options) as they seemed to have no use that I could find, and were not settable.

Not sure if you have any other ideas. But wanted to let you know the problems I hit.

**Comment by mlipok** [comment]
Take a look on my merge for resolving confilct:
[Merge branch 'main' into Images](https://github.com/mlipok/Au3LibreOffice/pull/47/commits/77d743036f6f42cdc1f6631faa2ddd7d1a99451e)

**Comment by donnyh13** [comment]
Okay

**Comment by donnyh13** [comment]
See comment I left in commit

**Comment by mlipok** [comment]
Please merge changes into your PR

**Comment by donnyh13** [comment]
Okay. Think I did.

**Pull request merged**
